# Basics of Python

In [1]:
# Esta celda da el estilo al notebook
from IPython.core.display import HTML
css_style = r'..\style_1.css'
css_file =  css_style
HTML(open(css_file, "r").read())

## 1. Types of simple objects

Everything in Python is an object. This includes the numbers, characters, figures, etc. Concretely, they are classes. The syntax and how it works for numbers and strings is pretty similar to Matlab.

In [2]:
a = 7       # This is a number
b = 'Seven' # This is a string
type(b)

str

However, we must be aware of some small differences. For example, if we ask for the type of `a`.

In [3]:
type(a)

int

It is a number, yeah, but it is not any number. It is an integer. If we now have this:

In [4]:
c = 7.0
type(c)

float

Then we have another type of number. Sometimes, these can produce errors when working with different numeric data. It is important to have this in mind. For example, a simple `for`loop:

In [5]:
for i in range(a):
    print(i)

0
1
2
3
4
5
6


Now try this:

```python
for i in range(c):
    print(i)
```

There we have a problem. We must convert the number to one that it can be understood.

In [6]:
for i in range(int(c)):
    print(i)

0
1
2
3
4
5
6


As you may have noticed, there is another important difference with `MATLAB`. In the `for` loop, the initial value was 0, not 1. This will happen for all the multipart objects. For example, if we have the folowing string: 

In [7]:
text = 'Infeasible'
print('The first letter is:', text[0])

The first letter is: I


Additionally, differently from `MATLAB`, the partitions of an object are selected using `[]`, and not `()`. Since we are on the subject, these are a few shortcuts:

In [8]:
print('The last letter:', text[-1])
print('All but the first letter:', text[1:])  # Notice that the left side of : includes it
print('All but the last letter:', text[:-1])  # The right side does not include it
print('From the second letter to the before last:', text[1:-1])

The last letter: e
All but the first letter: nfeasible
All but the last letter: Infeasibl
From the second letter to the before last: nfeasibl


Of course, these partitions also work with matrices, as we will see.

## 2. Lists and arrays

Now, a big difference. Lists. Matlab does not have lists. What you get in Matlab from doing this:

```matlab
A = [1, 'a', 1.2]
```

Is a big error. In red. This is because Matlab operates with matrices by default. And there is no matrix of strings and numbers. However, if you are using a list, they can be possible:

In [9]:
simple_list = [1, 'a', 1.2]
print(simple_list)

[1, 'a', 1.2]


So is a list a super matrix? Nope. It is a list. And it's best seen when you see the following:

In [10]:
a = [1,2,3]
b = [2,3,4]
print(a+b)

[1, 2, 3, 2, 3, 4]


That is a weird vector sum. Very weird, actually. The thing is, that adding a list to another list only appends the elements. If we want to use vectors, matrices (Arrays), we must import them from the Numerical Python package `numpy`.

In [11]:
import numpy as np
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a+b)

[3 5 7]


So, a `numpy.array` is MATLAB, right? Yes and no. Numpy arrays are formed with lists, so their sintaxis is a bit more strict and long than Matlab. For example, if you want a 2x2 matrix in matlab, you just write this:

```Matlab
A = [1 3; 4 5]
```

The same matrix in python would be:

In [12]:
A = np.array([[1,3],[4,5]])
print(A)

[[1 3]
 [4 5]]


Notice this is a **nested list**. This meaning, the list would be:

In [13]:
A_list = [[1,3],[4,5]]

This list can be splitted however you want. This is a list with two lists inside.

In [14]:
print('The first list is:', A_list[0])
print('The second list is:', A_list[1])
print('The first element of the first list is:', A_list[0][0])

The first list is: [1, 3]
The second list is: [4, 5]
The first element of the first list is: 1


Now, the matrix has the same things. But includes a more intuitively one, from Matlab.

In [15]:
print('The first list is:', A[0])
print('The second list is:', A[1])
print('The first element of the first list is:', A[0][0])
print('But it can also be written:', A[0,0])

The first list is: [1 3]
The second list is: [4 5]
The first element of the first list is: 1
But it can also be written: 1


We won't be using matrices with Pyomo. But we will use a lot of lists. So it is important to get the slicing right.

Just as an informative datum. In Python, there exist 1-D vectors. For example:

In [16]:
a.shape

(3,)

This is neither a row nor a column vector. It's a 1D vector. Something to take into account when performing matrix multiplication.

In [17]:
np.dot(a,a)   # Two 1-D are multiplied in a manner that it makes sense.

14

In [18]:
b = np.array([1,2])
print(np.dot(b,A))  
print(np.dot(A,b))  # The vector form is changed depending on the dimensions.

[ 9 13]
[ 7 14]


## 3. Functions

Functions are the most widely used (after numbers and stuff) class. They allow to automate a lot of things. Their definition varies a bit from Matlab. In Matlab, you define a function with:

```matlab
function z = f(x,y)
end 
```

Where:

- `z`: Output of the function
- `x,y`: Inputs of the function

In Python, the output is defined at the end of the function.

In [19]:
def f(x,y):
    return x+y

We don't need to define the output with another name if we don't want to:

In [20]:
f(3,2)

5

## 4. Conditionals and Loops

In the same manner as in other languages, both `for` loops and `if` statements are widely used in Python. The standard syntaxis looks like:

In [21]:
for i in range(1,8):
    if i%2==0:
        print(i)

2
4
6


With multiple elements is a bit different:

In [22]:
array1 = np.array([True,False,True])
array2 = np.array([True,False,False])

In [23]:
array1 & array2

array([ True, False, False])

In [24]:
array1 | array2

array([ True, False,  True])

Common elements from a loop:

In [36]:
for i in range(0,3):
    print(i)
for n,i in enumerate(['hola', 'que', 'tal']):
    print(n,i)

0
1
2
0 hola
1 que
2 tal


Be careful with the difference between `range` and `in`:

In [39]:
values = [1,3,4,5]
for i in values:
    print(i)
print('----------------')
for i in range(len(values)):
    print(i)

1
3
4
5
----------------
0
1
2
3


A bit more advanced topic are list loops. For the following:

In [44]:
a = []
for i in range(3):
    a.append(i)
b = [i for i in range(3)]
print(a,b)

[0, 1, 2] [0, 1, 2]


This reduces a lot of time and space when writing loops:

In [45]:
k1 = []
[k1.append('k'+str(i)) for i in range(3)]
k2 = ['k'+str(i) for i in range(3)]
k3 = []
for i in range(3):
    k3.append('k'+str(i))
print(k1)
print(k2)
print(k3)

['k0', 'k1', 'k2']
['k0', 'k1', 'k2']
['k0', 'k1', 'k2']


## 5. Dictionaries

These are the main tools used to define sets in Pyomo. A dictionary is, continuing the analogy with MATLAB, a cell. They are defined by `{}`

In [25]:
dictionary = {}
dictionary

{}

You can create it with things already inside, or add the things once created. Dictionaries have two main parts. Keys and values. You can add any variable to a key, and even tuples. You can add anything to their values:

In [26]:
dictionary['a','b']= 2
dictionary['a'] = [2,3,4]
dictionary[18,29] = np.array([2,3,4])
dictionary[0] = 'Hello'
dictionary

{('a', 'b'): 2, 'a': [2, 3, 4], (18, 29): array([2, 3, 4]), 0: 'Hello'}

In [33]:
for i in dictionary:
    print('This takes the keys',i)
    print('This takes the values', dictionary[i])

This takes the keys ('a', 'b')
This takes the values 2
This takes the keys a
This takes the values [2, 3, 4]
This takes the keys (18, 29)
This takes the values [2 3 4]
This takes the keys 0
This takes the values Hello
